name: wf-usm-work-build

on:
  push:
   branches:
      - 'develop'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
#    - name: Build
 #     run: ./gradlew clean build
    - name: Create TAG
      run: "echo TAG=$(git rev-parse --short $GITHUB_SHA) > $GITHUB_ENV"
    - name: Saving TAG for CD
      run: |
           sed -i 's/VAR1.*/TAG=${{ env.TAG }}/g' .github/resources/env.txt
           cat .github/resources/env.txt
    - name: Create Docker Image
      run: docker build -t 5927055/usm-work:${{ env.TAG }} .
    - name: Docker Login 
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
 
    - name: Push Artifact To Docker Hub
      run:  docker push 5927055/usm-work:${{ env.TAG }}
  